# Generated by Django 3.0.1 on 2019-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articlecomment_blogarticle_event_sitearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitearticle',
            name='brief',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
