# Generated by Django 3.0.1 on 2020-01-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191230_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitearticle',
            old_name='changed',
            new_name='posted',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='brief',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='sitearticle',
            name='brief',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
