# Generated by Django 3.0.1 on 2020-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200101_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
