# Generated by Django 3.0.1 on 2019-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitearticle_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitearticle',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
