# Generated by Django 3.0.1 on 2019-12-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitearticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitearticle',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitearticle',
            name='section',
            field=models.IntegerField(choices=[(0, 'home'), (1, 'class')]),
        ),
    ]
