# Generated by Django 3.0.1 on 2020-01-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0006_auto_20200102_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='associate_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
