# Generated by Django 3.0.1 on 2019-12-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0008_auto_20191221_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
